### ISSUE TITLE
Laravel 10 Support?

### ISSUE THREAD

**Issue by Supernova3339** [headerx/laravel-jetstream-passport#4]
Hi, this package is awesome! I'm curious if Laravel 10 support is planned as that would be awesome!

Please let me know if there's anything I need to do to make this possible.

**Comment by seomikewaltman** [comment]
Agreed this is bad ass. Should be incorporated into Jetstream as an option instead of Sanctum being hardcoded into it!

**Comment by inmanturbo** [comment]
Done.

Thanks! I'm sorry I hadn't realized this package had become so popular. I'll start keeping it up to date.

PR's Welcome!

**Comment by inmanturbo** [comment]
Please @ me if there are any issues with Laravel 10 or 11. I'll set up a workflow for testing the stubs soon.
